name: Test

on:
  push:
    branches:
      - master

jobs:
  run-test-vm:
    name: Run Test in VM
    runs-on: ubuntu-latest

    container:
      image: golang:alpine

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Test
        run: CGO_ENABLED=0 go test -race ./...
        env:
          REDIS_ADDRESS: "redis:6379"
          REDIS_PASSWORD: ""